# Generated by Django 6.0.6 on 2026-07-26 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('WEEKLY', 'weekly'), ('QUIZ', 'quiz'), ('PROJECT', 'project')], default='WEEKLY', max_length=50)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_activity', to='classes.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('INDIVIDUAL', 'individual'), ('GROUP', 'group')], default='INDIVIDUAL', max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deadline', models.DateTimeField()),
                ('submission_limit', models.PositiveIntegerField(default=1)),
                ('answer_type', models.CharField(choices=[('TEXT', 'text'), ('FILE', 'file'), ('CODE', 'code')], max_length=20)),
                ('late_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('save_to_bank', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField(blank=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individyal_scores', to='classes.membership')),
                ('scored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriterias', to='assignments.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submission/files')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
            ],
        ),
    ]
