# Generated by Django 6.0.6 on 2026-08-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
