# Generated by Django 6.0.6 on 2026-08-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_activitybudget_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybudget',
            name='created_at',
        ),
    ]
