# Generated by Django 6.0.6 on 2026-10-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_activitybudget_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assignments.submission'),
        ),
    ]
